# Site settings
title: "Edisson Giovanni Zuñiga Lopez - Arquitecto DevOps"
description: "Arquitecto DevOps Senior con más de 10 años de experiencia en infraestructura, CI/CD, Docker, Kubernetes y metodologías ágiles."
baseurl: "/Edisson-Giovanni-Z-Lopez"
url: "https://giovanemere.github.io"

# Author information
author:
  name: "Edisson Giovanni Zuñiga Lopez"
  email: "giovanemere@gmail.com"
  bio: "Arquitecto DevOps Senior especializado en infraestructura cloud, CI/CD, Docker, Kubernetes y metodologías ágiles."
  location: "Zipaquirá, Colombia"
  linkedin: "edissonzuniga"
  github: "giovanemere"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Theme
theme: jekyll-theme-architect

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: es
locale: es_CO

# Social media
social:
  name: Edisson Giovanni Zuñiga Lopez
  links:
    - https://github.com/giovanemere
    - https://www.linkedin.com/in/edissonzuniga/

# Google Analytics (uncomment and add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md

# Include files
include:
  - _pages

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Edisson Giovanni Zuñiga Lopez"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  verbose: false

# Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false